#!/bin/bash

#Initalize TLS 1.2
screen -S HL -X stuff 'AT+KSSLCFG=0,3'$(echo -ne '\015')		#set to TLS1.2
sleep .1
screen -S HL -X stuff 'AT+KSSLCFG?'$(echo -ne '\015')			#0,3 and 2,0 means ready 
sleep .1

#Store CA Certificate to Root
screen -S HL -X stuff 'AT+KCERTSTORE=0'$(echo -ne '\015')
sleep .1

#./lib/exe/PrintFileLocal -f lib/Certificates/Vietnamese\ Keys/WIPSoft_CA_Cert.txt
./lib/exe/PrintFileLocal -f lib/Certificates/FireBaseKeys/GlobalSign_Root 

screen -S HL -X stuff '--EOF--Pattern--'$(echo -ne '\015')
sleep 2

#Store Client Certificate to Local
screen -S HL -X stuff 'AT+KCERTSTORE=1,,0'$(echo -ne '\015')
sleep .1

#./lib/exe/PrintFileLocal -f lib/Certificates/Vietnamese\ Keys/WIPSoft_Client_Cert.txt
./lib/exe/PrintFileLocal -f lib/Certificates/FireBaseKeys/GTS_CA_101

screen -S HL -X stuff '--EOF--Pattern--'$(echo -ne '\015')
sleep 2

screen -S HL -X stuff 'AT+KCERTSTORE?'$(echo -ne '\015')
sleep .1

#Store Client Private Key
screen -S HL -X stuff 'AT+KPRIVKSTORE=0'$(echo -ne '\015')
sleep .1

./lib/exe/PrintFileLocal -f lib/Certificates/FireBaseKeys/domain.txt

screen -S HL -X stuff '--EOF--Pattern--'$(echo -ne '\015')
sleep 2

screen -S HL -X stuff 'AT+KPRIVKSTORE?'$(echo -ne '\015')
sleep 1

#Setup Module Clock
screen -S HL -X stuff 'AT+CCLK="19/11/16,14:52:43-24"'$(echo -ne '\015')
sleep .1

#Setup Module 

screen -S HL -X stuff 'AT+CGDCONT=1,"IP","internet.sierrawireless.com",,0,0,0,2,1,0,0,0,1,1,1,1'$(echo -ne '\015')
sleep 1

#screen -S HL -X stuff 'AT+KCNXCFG=1,"GPRS","internet.sierrawireless.com"'$(echo -ne '\015')
screen -S HL -X stuff 'AT+KCNXCFG=1,"GPRS","internet.sierrawireless.com",,,"IPV4","","8.8.8.8","","","",""'$(echo -ne '\015')
sleep .1

screen -S HL -X stuff 'AT+KCNXPROFILE=1'$(echo -ne '\015')
sleep 3

#Check that module has IP address
screen -S HL -X stuff 'AT+CGPADDR=1'$(echo -ne '\015')
sleep .1

#Setup SSL Configuration
screen -S HL -X stuff 'AT+KSSLCRYPTO=0,9,3,25456,12,4,0'$(echo -ne '\015')
sleep 1

#Setup HTTP Configuration
	# Trust DNS Server
screen -S HL -X stuff 'AT+KHTTPCFG=1,"www.mitelight-app.firebaseio.com",443,2,,,,,0'$(echo -ne '\015')
	# Provide IP Address
#screen -S HL -X stuff 'AT+KHTTPCFG=1,"35.201.97.85",443,2,,,,,0'$(echo -ne '\015')
sleep 5


#Setup HTTP header Sample Field
screen -S HL -X stuff 'AT+KHTTPHEADER=1'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'Content-Length: 44'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff '--EOF--Pattern--'$(echo -ne '\015')
sleep .1

#Run HTTP Post to Send Data to HTTPS Server
screen -S HL -X stuff 'AT+KHTTPPOST=1,,"\post\"'$(echo -ne '\015')
sleep 1
screen -S HL -X stuff 'This line is the HTTP POST data test vector.'$(echo -ne '\015')
sleep 5
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1

#Run HTTP Header Check
screen -S HL -X stuff 'AT+KHTTPHEAD=1,"\"'$(echo -ne '\015')
sleep 5
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1

screen -S HL -X stuff 'AT+KHTTPDEL=1'$(echo -ne '\015')
sleep .1
