#!/bin/bash

#Initalize TLS 1.2
screen -S HL -X stuff 'AT+KSSLCFG=0,3'$(echo -ne '\015')		#set to TLS1.2
sleep .1
screen -S HL -X stuff 'AT+KSSLCFG?'$(echo -ne '\015')			#0,3 and 2,0 means ready 
sleep .1

#Store CA Certificate 
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT'$(echo -ne '\015')
sleep .1
