#!/bin/bash

#screen -S HL -X stuff 'AT+CFUN=1,1'$(echo -ne '\015')
#sleep 10

screen -S HL -X stuff 'ATI3'$(echo -ne '\015')
sleep .1

screen -S HL -X stuff 'AT+KCERTSTORE?'$(echo -ne '\015')
sleep 2

#screen -S HL -X stuff 'AT+CCLK="19/11/15,22:15:32-24"'$(echo -ne '\015')
#sleep .1

screen -S HL -X stuff 'AT&K3'$(echo -ne '\015')
sleep .1

#screen -S HL -X stuff 'AT+CGATT=0'$(echo -ne '\015')
#sleep 5

screen -S HL -X stuff 'AT+KCNXCFG=1,"GPRS","internet.sierrawireless.com"'$(echo -ne '\015')
sleep 1

#screen -S HL -X stuff 'AT+KCNXUP=1'$(echo -ne '\015')
#sleep 10

#screen -S HL -X stuff 'AT+KSSLCRYPTO=5,1,1,8192,4,4,0'$(echo -ne '\015')
#sleep 2

#screen -S HL -X stuff 'AT+KSSLCFG=0,3'$(echo -ne '\015')
#sleep 2

screen -S HL -X stuff 'AT+KTCPCFG=1,3,"mitelight-app.firebaseio.com",443'$(echo -ne '\015')
sleep 1

AT+KTCPCFG=1,3,"howsmyssl.com",443,,,,,0

#,,,,,0

screen -S HL -X stuff 'AT+KTCPCNX=1'$(echo -ne '\015')
sleep 10

screen -S HL -X stuff 'AT+KTCPSND=1,18'$(echo -ne '\015')
sleep .1

screen -S HL -X stuff 'HTTP/1.1 200 OK<CR><LF>'$(echo -ne '\015')
sleep .1

#screen -S HL -X stuff 'GET / HTTP/1.0\r\n\r\n--EOF–-Pattern--'$(echo -ne '\015')
#sleep .1

screen -S HL -X stuff '{"request": abcsCR><LF>}'$(echo -ne '\015')
sleep .1

screen -S HL -X stuff '--EOF--Pattern--'$(echo -ne '\015')
sleep .1



screen -S HL -X stuff 'AT+KTCPRCV=1,103'$(echo -ne '\015')
sleep 3

screen -S HL -X stuff 'AT+KTCPRCV=1,1380'$(echo -ne '\015')
sleep 3

screen -S HL -X stuff 'AT+KTCPRCV=1,1380'$(echo -ne '\015')
sleep 3

screen -S HL -X stuff 'AT+KTCPCLOSE=1,1'$(echo -ne '\015')
sleep 1

screen -S HL -X stuff 'AT+KTCPDEL=1'$(echo -ne '\015')
sleep .1

screen -S HL -X stuff 'AT+KTCPCFG?'$(echo -ne '\015')
sleep .1

