#!/bin/bash

screen -S HL -X stuff 'AT+KSSLCFG=0,0'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AT+KCERTSTORE=0,2004,0'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff '-----BEGIN CERTIFICATE-----'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'MIIFmzCCBIOgAwIBAgIRAJRuZHok8dQjAQAAAAApJGwwDQYJKoZIhvcNAQELBQAw'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'QjELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczET'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'MBEGA1UEAxMKR1RTIENBIDFPMTAeFw0xOTAzMTMyMTMwNTdaFw0yMDAzMTEyMTMw'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'NTdaMGgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'Ew1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKEwpHb29nbGUgTExDMRcwFQYDVQQDEw5m'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'aXJlYmFzZWlvLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALkd'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff '/jeM+PrwIYmM6IE28iN7CjKnBWy+tqNrs5z2AJwM5iLgtgcbc+THuXGElTN7zAWB'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'SKWv+ezAGe5NiTEEUiWgX1z1VFDj85xpz+Cysn/Oi8MtoN6h8yCmYPtXv8YPInw0'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'JLkSM5e2uuWVwc/tR1Fh+awpiYQFqGm6DvMq6yAYB/nuL3Gyc4XFgRrxje+VQ+g3'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'oWE+9NVfqu4smFCutSIGlEdRhGdr/m2u+sc+dnBZNoVOqwSyyFyjpAZvMMvuE5Ip'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff '3ovfA1tq57nl9eQw8fcKsdXOeeXYHc1KBUUC7Xb8F/1+upVML8a5GMULpYkClLXt'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'OKRRfCJa53YynILJdPkCAwEAAaOCAmQwggJgMA4GA1UdDwEB/wQEAwIFoDATBgNV'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBS03YhV70g6'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff '+7MUxtOiluRi1T2GAzAfBgNVHSMEGDAWgBSY0fhuEOvPm+xgnxiQG6DrfQn9KzBk'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'BggrBgEFBQcBAQRYMFYwJwYIKwYBBQUHMAGGG2h0dHA6Ly9vY3NwLnBraS5nb29n'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'L2d0czFvMTArBggrBgEFBQcwAoYfaHR0cDovL3BraS5nb29nL2dzcjIvR1RTMU8x'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'LmNydDArBgNVHREEJDAigg5maXJlYmFzZWlvLmNvbYIQKi5maXJlYmFzZWlvLmNv'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'bTAhBgNVHSAEGjAYMAgGBmeBDAECAjAMBgorBgEEAdZ5AgUDMC8GA1UdHwQoMCYw'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'JKAioCCGHmh0dHA6Ly9jcmwucGtpLmdvb2cvR1RTMU8xLmNybDCCAQIGCisGAQQB'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff '1nkCBAIEgfMEgfAA7gB1ALIeBcyLos2KIE6HZvkruYolIGdr2vpw57JJUy3vi5Be'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'AAABaXkuFzgAAAQDAEYwRAIgVssWhLEYItcpljMfJfkBhnxUrw32ik3C7IyBhkS6'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'jQcCIAHzoq/0QsRXY8RITJ5z6pThPzJhiSeLhWb6v2MDs6+NAHUAXqdz+d9WwOe1'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'Nkh90EngMnqRmgyEoRIShBh1loFxRVgAAAFpeS4XEQAABAMARjBEAiBgwY3jVuyU'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'HTDrfXt7Hhq3AL9kD8hASq/qIXFvHAel1AIgV2DY0UI7PvVl2uHicvaL9BfUPQjP'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff '8/7b5W5jd6HEKbowDQYJKoZIhvcNAQELBQADggEBAAFG/f9zTyPTiYjjbPKpIC3T'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'MMD8dWvny1DJpL2fQPMcpAkkduW7sFG8mLRh14mSBsWqAusj99nAKt6NJhxZewhp'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'JKwbcawanW+w2DUzFr0FauVxNIs4xPxcgkCNAGeUj8ZI+cDcSaMOY4WxNrjOgbbI'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'feOxHsCmIWxch6/vNVxh+54BZFCy723DL8Fo/tDRU73b+gxPJusJva4ABuXSqSFT'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'EDaRGzdj8AKkoDmRkWLcEg/6a/2dfw8VV7fIAlqVxNQwZWZLtIsBGazxZ5xflrVz'$(echo -ne '\015')
sleep .1
screen -S HL -X stuff 'I5AHejNR7guDaWAimhkSOlG11W8BzPtdAo/xJ6JyI4K5kPGIXucniVRmQfmojxc='$(echo -ne '\015')
sleep .1
screen -S HL -X stuff '-----END CERTIFICATE-----'$(echo -ne '\015')
sleep 1
screen -S HL -X stuff 'AT+KCERTSTORE?'$(echo -ne '\015')


# Sanity Check
# screen -S HL -X stuff 'AT'$(echo -ne '\015')

