#!/bin/bash

#Delete Old Root/Local Certificates
screen -S HL -X stuff 'AT+KCERTDELETE=0,0'$(echo -ne '\015')
sleep 1
screen -S HL -X stuff 'AT+KCERTDELETE=1,0'$(echo -ne '\015')
sleep 1
screen -S HL -X stuff 'AT+KCERTDELETE=1,1'$(echo -ne '\015')
sleep 1
screen -S HL -X stuff 'AT+KCERTDELETE=1,2'$(echo -ne '\015')
sleep 1
