#!/bin/bash

#Initalize TLS 11
screen -S HL -X stuff 'AT+KSSLCFG=0,3'$(echo -ne '\015')				#set to TLS1.2
sleep 1

screen -S HL -X stuff 'AT+KSSLCFG?'$(echo -ne '\015')			#0,3 and 2,0 means ready 
sleep 1

#Validate Certificate Store

screen -S HL -X stuff 'AT+KCERTSTORE?'$(echo -ne '\015')
sleep 1

#Soft Restart

screen -S HL -X stuff 'AT+CFUN=0'$(echo -ne '\015')
sleep 5

screen -S HL -X stuff 'AT+CFUN=1'$(echo -ne '\015')
sleep 5

#Setup Module Clock
screen -S HL -X stuff 'AT+CCLK="19/11/16,14:52:43-24"'$(echo -ne '\015')
sleep 1

#Check that module has IP address
screen -S HL -X stuff 'AT+CGPADDR=1'$(echo -ne '\015')
sleep 1

#Setup Module 
screen -S HL -X stuff 'AT+CGDCONT=1,"IP","internet.sierrawireless.com",,0,0,0,2,1,0,0,0,1,1,1,1'$(echo -ne '\015')
sleep 1

screen -S HL -X stuff 'AT+KCNXCFG=1,"GPRS","internet.sierrawireless.com",,,"IPV4"'$(echo -ne '\015')
sleep 1

#Setup SSL Configuration
screen -S HL -X stuff 'AT+KSSLCRYPTO=0,9,3,25456,12,4,0'$(echo -ne '\015')
sleep 1

screen -S HL -X stuff 'AT+KCNXUP=1'$(echo -ne '\015')
sleep 5

#Setup HTTPS Configuration

		#DNS Resolution
#screen -S HL -X stuff 'AT+KHTTPCFG=1,"www.mitelight-app.firebaseio.com",443,2,,,,,0'$(echo -ne '\015')
		# Don't trust DNS
screen -S HL -X stuff 'AT+KHTTPCFG=1,"35.201.97.85",443,2,,,,,0'$(echo -ne '\015')
sleep 2

#Run HTTP Get Data from HTTPS Server
screen -S HL -X stuff 'AT+KHTTPGET=1,"/"'$(echo -ne '\015')
sleep 7

screen -S HL -X stuff 'AT+KHTTPDEL=1'$(echo -ne '\015')
sleep 1
